const enUS = {
  'welcome' : 'Welcome to the Note App!',
  'create_note': 'Create a new note.',
  'view_all_notes': "View all notes.",
  'settings': "Settings",
  'exit': "Exit the program.",
  'error': "Error command entered",
  'new_note_name': "Enter a name for the new note: ",
  'file_error': "The note name entered was previously created, please try again.",
  'write_note': "You can write on the note. (Type 'save' to save):",
  'save': 'save',
  'note_save': "Note successfully saved!",
  'number_note': "Enter the Note number",
  'delete_all': "Delete all notes",
  'delete_selected': "Selective deletion",
  'no_note': "No notes yet!",
  'back_to_home': "Return to the main menu.",
  'enter_note_number': "Enter the Note number: ",
  "update": "Edit",
  "delete": "Delete",
  "back_to": "Back to",
  'edit_note': "You can change note:",
  'previous_note': "Previous note:",
  'success_delete_all': "All files deleted successfully!",
  'select_file': "Select the directory file number and enter:",
};