const uzUZ = {
  'welcome' : 'Note Appga Xush Kelibsiz!',
  'create_note': 'Yangi noteni yarating.',
  'view_all_notes': "Barcha notelarni ko'rish.",
  'settings': "Sozlamalar",
  'exit': "Dasturdan chiqish.",
  'error': "Xato buyruq kiritildi",
  'new_note_name': "Yangi noteni nomini kiriting: ",
  'file_error': "Kiritilgan note nomi oldin yaratilgan, Iltimos qayta urunib ko'ring.",
  'write_note': "Notega yozishingiz mumkin. (Saqlash uchun 'save' so'zini yozing): ",
  'save': 'save',
  'note_save': "Note muvoffaqiyatli saqlandi!",
  'number_note': "Note raqamini kiriting",
  'delete_all': "Barcha notelarni o'chirish",
  'delete_selected': "Tanlab o'chirish",
  'no_note': "Hozircha notelar mavjud emas!",
  'back_to_home': "Bosh menuga qaytish.",
  'enter_note_number': "Note raqamini kiriting: ",
  "update": "O'zgartirish",
  "delete": "O'chirish",
  "back_to": "Ortga qaytish",
  'edit_note': "Note O'zgartirishingiz mumkin:",
  'previous_note': "Avvalgi note:",
  'success_delete_all': "Barcha fayllar muvoffaqiyatli o'chirildi!",
  'select_file': "Katalog file lar raqamini tanlab kiriting:",
};